### ISSUE TITLE
[Colab] Doesn't save checkpoints nor generate

### ISSUE THREAD

**Issue by TheAsterix** [rncm-prism/prism-samplernn#10]
When I train the RNN, checkpoints can't be saved, It also can't generate audio after epochs, even though I set checkpoint_every by 1 and generate to True. It only saves Tenderboard statistics.

**Comment by relativeflux** [comment]
@TheAsterix Hi, it should do all of those things. Which version are you using? Also are you using the Colab notebook? I would advise making a new copy of the latter, as there have been some changes to it, and also of course pulling the latest version of the code. Or just do a fresh clone to be absolutely sure. Thanks!

**Comment by TheAsterix** [comment]
I pulled the latest version of colab and git. Even checked git to be sure. I tried other settings for training. Still only logs

**Comment by relativeflux** [comment]
OK, thanks. I'm not seeing any problems with this myself... What do you have under logdir? You should have a folder related to each training id. There is a default folder there. Under each id-labelled folder you should have one time-stamped folder for each training run under the gven id. The checkpoints and tensorboard logs (train and validation) should be there too.

Using the default id (no id specified) I see this right now:

<img width="1104" alt="Screenshot 2020-12-20 at 06 31 18" src="https://user-images.githubusercontent.com/17030640/102706822-17ad7e00-428d-11eb-9b9b-f81cd158208d.png">

**Comment by TheAsterix** [comment]
![Screenshot_2020-12-20-09-34-14-254_com google android apps docs](https://user-images.githubusercontent.com/76261157/102706860-9f53b680-42a6-11eb-9447-cd59cf51309d.jpg)
Only have default. Inside theres timestamped folders with only logs in them

**Comment by relativeflux** [comment]
OK, do you have multiple time-stamped folders under default? If so are they all empty of checkpojnts?

What happens if you use an id other than the default?

**Comment by TheAsterix** [comment]
Yes. All of them are logs. Ill try to use the other ID now. Gonna reinstall the rnn. See how it goes

**Comment by TheAsterix** [comment]
![image](https://user-images.githubusercontent.com/76261157/102707519-c4e3be80-42ac-11eb-98f3-f40839ec0dde.png)
No checkpoint and model, after generating an epoch
![image](https://user-images.githubusercontent.com/76261157/102707527-d927bb80-42ac-11eb-954f-5ed4dd3e893b.png)
This is my settings for training

**Comment by relativeflux** [comment]
Ah, I can see what's happening now. It's the `--checkpoint_policy` param set to `Best`. This seems to not be working properly, I'm running a training on the notebook again now and with that set to `Best` indeed no checkpoint is saved. Apologies, I missed this, will fix.

**Comment by TheAsterix** [comment]
Trying "always" I'll see how it goes

**Comment by TheAsterix** [comment]
Now it has checkpoints. Thanks for help

**Comment by relativeflux** [comment]
No problem. I'll look into that and fix it ASAP.
