### ISSUE TITLE
Cannot change parameters in config.json 

### ISSUE THREAD

**Issue by Bienoise** [rncm-prism/prism-samplernn#11]
Dear @relativeflux ,
first of all, thanks a lot for taking the time in doing this! I'm a musician and a teacher, and I needed a working and well documented RNN to introduce my students to it.

I'm trying to train it on a (unfortunately small) batch of voice samples (20 minutes, in overlapped 4 seconds chunks).
As the default config.json wasn't giving me better accuracy results than ~32, I tried to modify it with your suggested LSTM + skip connections + linear quantization. I'm using the Colab.

I changed just those parameters, and I keep getting this error: 
> ValueError: Shapes (4096,) and (2, 3072) are incompatible

I'm fairly new to programming so it's entirely possible that I'm making some mistakes, but after two days I decided to ask you if it's a known issue.

Thank you, best!

**Comment by relativeflux** [comment]
Hi @Bienoise, thanks for gettinng in touch. Could you post your script parameters and the full cotnents of your config file?

**Comment by Bienoise** [comment]
Of course, sorry for not doing that already.
Right now I'm trying doing a new Notebook, will update as soon as I'm done. Thanks!

- config is like this:

{
    "seq_len": 1024,
    "frame_sizes": [16,64],
    "dim": 1024,
    "rnn_type": "lstm",
    "num_rnn_layers": 4,
    "q_type": "linear",
    "q_levels": 256,
    "emb_size": 256,
    "skip_conn": true
}

- train.py is like this (even if I tried various changes, in particular in batch size):

!python train.py \
  --data_dir /content/drive/MyDrive/prism-samplernn/chunks \
  --num_epochs 40 \
  --batch_size 32 \
  --max_checkpoints 5 \
  --checkpoint_every 10 \
  --output_file_dur 5 \
  --sample_rate 11025 \
  --resume True

**Comment by Bienoise** [comment]
UPDATE 
@relativeflux, as for the other closed discussion, creating a new Notebook and starting over worked! 
Your algorithm is now up and running.

Sorry for disturbing you, but at least I got the chance to say thanks.
Best!

**Comment by relativeflux** [comment]
@Bienoise Thank you, no problem at all. Indeed, there did seem to be an issue on the notebook, creating a new one seems to fix it.

By the way, how many chunks do you have in your dataset? My general advice now is to get as much data as you possibly can!

**Comment by Bienoise** [comment]
Right now I have 378 4-seconds chunks. I know I should get more, but unfortunately for this particular application I only got those 20 minutes of audio.
In the past I used to work on 2+ hours of field recordings with the old SampleRNN, I'm gonna try again with yours (which looks far better) as soon as I'm done with this project!

Hope I don't need to disturb you again!
Have a nice day.

**Comment by relativeflux** [comment]
Thanks for the info. I usually run it with in excess of 2000 chunks these days. I am currently researching different [data augmentation](https://en.wikipedia.org/wiki/Data_augmentation) strategies, hopefully will be able to add something soon.

**Comment by ahihi** [comment]
i had this exact same issue, but i'm not using colab at all. after training with LSTM + skip connections + linear quantization and trying to generate, i got the `Shapes (4096,) and (2, 3072) are incompatible` error.

turns out i didn't actually pass the modified config to train.py (due to a bug in my own wrapper script) so it ended up training with the default config. so apparently this error can be caused by a config mismatch between training and generation. hopefully that helps others who might run into this!
