### ISSUE TITLE
raise ValueError('Expect x to be a non-empty array or dataset.')

### ISSUE THREAD

**Issue by Squatnet** [rncm-prism/prism-samplernn#12]
Running in Collab fails with an error when executing train.py,
```Epoch 1/20
Traceback (most recent call last):
  File "train.py", line 332, in <module>
    main()
  File "train.py", line 323, in main
    verbose=0,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1110, in fit
    raise ValueError('Expect x to be a non-empty array or dataset.')
ValueError: Expect x to be a non-empty array or dataset.
```

**Comment by relativeflux** [comment]
Hi @Squatnet, what are your train.py script params, and also your config file settings (if different from the defaults)?

**Comment by Squatnet** [comment]
I'm just using the default arguments for train. 
I've since cloned the repo to an azure vm and its working fine on there but I just could not get train.py to launch.
Let me know if I can test it or anything for you, I'm on GMT usually.

**Comment by relativeflux** [comment]
@Squatnet I know that some users have been having issues with Colab since a recent update, could you try making a fresh copy of the notebook and cloning into it again? Sorry for the inconvenience.

**Comment by relativeflux** [comment]
@Squatnet Hi, did you manage to resolve this?

**Comment by Squatnet** [comment]
No I ended up doing what I needed to do on an azure vps.

**Comment by parthlathiya42** [comment]
**Had the same error:**
`File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1110, in fit
    raise ValueError('Expect x to be a non-empty array or dataset.')
ValueError: Expect x to be a non-empty array or dataset.`

First tried reducing the batch size. If the batch size is bigger than the training dataset, then input dataset is not created and hence remain empty. But mine was not that case.

Then I tried to see where my dataset becomes empty. My first epoch ran fine but not another. Seems my dataset got transformed in batching process. 

```
classes = len(y.unique())

# model architecture
model = Sequential()
model.add(Dense(10, activation='relu',
    activity_regularizer=tf.keras.regularizers.l1(0.00001)))
model.add(Dense(classes, activation='softmax', name='y_pred'))

# this controls the learning rate
opt = Adam(lr=0.0005, beta_1=0.9, beta_2=0.999)
# this controls the batch size, or you can manipulate the tf.data.Dataset objects yourself
BATCH_SIZE = 12
print(train_dataset)
print(validation_dataset)
train_dataset, validation_dataset = set_batch_size(BATCH_SIZE, train_dataset, validation_dataset)

# train the neural network
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
model.fit(_train_dataset, epochs=10, validation_data=_validation_dataset, verbose=2, callbacks=callbacks)
```

**Solution for this case:**
Updated redundant updation of train and validation dataset while dividing it in batch by giving different name.

Before:
`train_dataset, validation_dataset = set_batch_size(BATCH_SIZE, train_dataset, validation_dataset)`

After:
'_train_dataset, _validation_dataset = set_batch_size(BATCH_SIZE, train_dataset, validation_dataset)'



`classes = len(y.unique())

# model architecture
model = Sequential()
model.add(Dense(10, activation='relu',
    activity_regularizer=tf.keras.regularizers.l1(0.00001)))
model.add(Dense(classes, activation='softmax', name='y_pred'))

# this controls the learning rate
opt = Adam(lr=0.0005, beta_1=0.9, beta_2=0.999)
# this controls the batch size, or you can manipulate the tf.data.Dataset objects yourself
BATCH_SIZE = 12
print(train_dataset)
print(validation_dataset)
_train_dataset, _validation_dataset = set_batch_size(BATCH_SIZE, train_dataset, validation_dataset)

# train the neural network
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
model.fit(_train_dataset, epochs=10, validation_data=_validation_dataset, verbose=2, callbacks=callbacks)`

**Comment by relativeflux** [comment]
@parthlathiya42  Thank you for this, I'm not in front of a machine where I can test this right now, but I think this mght relate to the validation dataset size, and how that is currently calculated. In the current master it is computed using the `num-val_batches` param, which defaults to 1. So the validation set must be at least 1 batch in size. Maybe your dataset is not large enough to accommodate a validation split of 1 batch in size.

This way of comuting the val dataset size is changing in the next week. I am about to merge a change which ensures that the validation set size is computed as a percentage (by default 10%, or a 0.1 fraction) of the total dataset size. This will then be rounded to the closest multiple of the batch size. This is a much more robust way of handling this. So there will be a new param `val_frac`, which defaults to 0.1.
