### ISSUE TITLE
Running on AMD GPU with ROCm

### ISSUE THREAD

**Issue by jaaaamIron** [rncm-prism/prism-samplernn#17]
Hi - this is more of a question than an issue. I'm going to try running SamplerRNN on Ubuntu but with an AMD GPU using the Tensorflow 2.0 compatibility built into Open ROCm by AMD (there's also PlaidML, but AFAIK that isn't so happy with Tensorflow 2.0). I was wanting to ask whether the developer was aware of anybody attempting this/whether they were successful etc? My main reason for trying this is to be able to use mac hardware to train. Thanks!

**Comment by relativeflux** [comment]
@jaaaamIron Hi, thanks for the quation. Indeed I've a few queries about this, and had wondered about it myself. I don't know of anyone who has actually tried, however. PRiSM SampleRNN leverages the TensrFlow Keras impementation quite heavily, so I guess it depends whether that will be available. It looks like it's available in  [ROCmSoftwarePlatform/tensorflow-upstream](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream), at least.
