### ISSUE TITLE
Error while training and generating data

### ISSUE THREAD

**Issue by bstivic** [rncm-prism/prism-samplernn#2]
I have problems with generating. Seems like error because of initialisation of default values of SampleRNN object?

Traceback (most recent call last):
  File "generate.py", line 175, in <module>
    main()
  File "generate.py", line 171, in main
    args.sample_rate, args.temperature, args.seed, args.seed_offset)
  File "generate.py", line 162, in generate
    model = create_inference_model(ckpt_path, num_seqs, config)
  File "generate.py", line 151, in create_inference_model
    emb_size=config['emb_size'],
TypeError: __init__() missing 2 required positional arguments: 'rnn_type' and 'skip_conn'

**Comment by relativeflux** [comment]
Hi,

Yes, this is fixed in https://github.com/rncm-prism/prism-samplernn/commit/d7275e8bb84c6f5ba5b20ed8ea80b8d7c5def2d0.

Skip connections are not in master yet, they're implemented on a new branch. It's published if you want to check it out.

Thanks
