### ISSUE TITLE
Problem when generating audio for new epoch

### ISSUE THREAD

**Issue by deccolquitt** [rncm-prism/prism-samplernn#20]
Traceback (most recent call last):
  File "train.py", line 335, in <module>
    main()
  File "train.py", line 326, in main
    verbose=0,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1229, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py", line 435, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/content/gdrive/My Drive/prism-samplernn/callbacks.py", line 103, in on_epoch_end
    self._generate(ckpt_path, self.generation_args)
  File "/content/gdrive/My Drive/prism-samplernn/callbacks.py", line 109, in _generate
    args['temperature'], args['seed'], args['seed_offset'])
  File "/content/gdrive/My Drive/prism-samplernn/generate.py", line 135, in generate
    file_name = f'{file_name}_t={temperature[i][0]}.wav'
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

**Comment by relativeflux** [comment]
@deccolquitt Hi, looks like a problem with the value being passed to temperature parameter. Could you post how you're calling the train.py script, with the parameters? Thanks.

**Comment by relativeflux** [comment]
@deccolquitt OK I can see what's causing it - I'm assuming you weren't explicitly passing a temperature value. I've identified a bug in that circumstances, am fixing it now.

**Comment by deccolquitt** [comment]
Hi, thanks for getting back so quickly, just in case you need it, here are the parameters I was using anyway:

!python train.py \
  --data_dir ./chunks \
  --num_epochs 100 \
  --batch_size 64 \
  --max_checkpoints 2 \
  --checkpoint_every 1 \
  --output_file_dur 5 \
  --sample_rate 16000

**Comment by relativeflux** [comment]
Thanks, that's just as I expected. It would be using the default temperature if you don't explicitly set it (either as a list or as one float value), but the default value was not being passed down internally in the correct format

Should work fine now, just pushed the fix.

**Comment by deccolquitt** [comment]
brilliant, will it try tomorrow

**Comment by relativeflux** [comment]
BTW, we're experimenting with replacing the default config params, you might want to try these:

```
{
    "seq_len": 512,
    "frame_sizes": [2,8],
    "dim": 1024,
    "rnn_type": "gru",
    "num_rnn_layers": 1,
    "q_type": "mu-law",
    "q_levels": 256,
    "emb_size": 256
}
```

These worked well for our [Beethoven Piano Sonata model](https://www.rncm.ac.uk/research/research-centres-rncm/prism/prism-collaborations/prism-samplernn/beethoven-32-piano-sonatas-reimagined/), though as always YMMV.
