### ISSUE TITLE
Issue modifying original .json file or replacing with a new one

### ISSUE THREAD

**Issue by xxrraa** [rncm-prism/prism-samplernn#28]
Hello, and thanks for this amazing release and the Colab!  I have been using the Colab for a while now and haven't messed with the config file until recently.  My problem occurs when I am trying to change "skip_conn" to True in the config.  I am sure the formatting of how I added "skip_conn" to the .json file was correct, I tried having True with and without quotations around it.    Even tried creating a new json with a new name and adding the new config file name to the arguments when training.  Nothing worked.  I also looked at an older issue here which talked about skip connections, and used the updated Colab and still got the same error

Would greatly appreciate your help on this and I thank you for your time.  

** **Config file & Train args below** **

{
    "seq_len": 1024,
    "frame_sizes": [16,64],
    "dim": 1024,
    "rnn_type": "gru",
    "num_rnn_layers": 4,
    "q_type": "mu-law",
    "q_levels": 256,
    "emb_size": 256,
    "skip_conn": "True"
}

!python train.py \
  --data_dir ./chunks/kick_hat_slices/ \
  --num_epochs 100 \
  --batch_size 128 \
  --max_checkpoints 7 \
  --checkpoint_every 1 \
  --generate False \
  --id "LSTM_kick_hat" \
  --resume False \

** **Error code below** **

Traceback (most recent call last):
  File "train.py", line 347, in <module>
    main()
  File "train.py", line 327, in main
    model(init_data)
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/content/drive/My Drive/prism-samplernn/samplernn/model.py", line 125, in call
    tf.cast(inputs, tf.float32)[:, : -self.big_frame_size, :]
  File "/content/drive/My Drive/prism-samplernn/samplernn/frame_rnn.py", line 47, in call
    frame_outputs = self.rnn(input_frames)
  File "/content/drive/My Drive/prism-samplernn/samplernn/nn.py", line 85, in call
    out += self.run_dense(name, seqs)
  File "/content/drive/My Drive/prism-samplernn/samplernn/nn.py", line 72, in run_dense
    dense = self.__getattribute__(name + '_skip_out')
AttributeError: Exception encountered when calling layer "rnn" (type RNN).

'RNN' object has no attribute 'layer_0_skip_out'

Call arguments received:
  • inputs=tf.Tensor(shape=(32, 16, 1024), dtype=float32)

**Comment by relativeflux** [comment]
@xxrraa Hi, and thanks for getting in touch about this. Since the config file is JSON for that param you'll need:

`"skip_conn": true`

Lower case and no quotes. `True` is Python format. :) Just tested that on Colab and I get the same error.

**Comment by xxrraa** [comment]
Wow you are a legend, thank you so so much.  <3
