### ISSUE TITLE
Generating: "AssertionError: Some objects had attributes which were not restored:"

### ISSUE THREAD

**Issue by curingd** [rncm-prism/prism-samplernn#3]
Hi,

I'm having problems generating a WAV file with the error message copied at the bottom.
It's perfectly possible I'm doing something very stupid because I'm a musician with minimal coding experience! I'm going off the Google Colab file which is here along with the settings I've changed:

https://colab.research.google.com/drive/1JLWJhgFSrhUxzrQ3PCciy5CBBgsxTdQk?usp=sharing

Thanks so much for this! It's going to give me so many options creatively if it works.

Traceback (most recent call last):
  File "generate.py", line 177, in <module>
    main()
  File "generate.py", line 173, in main
    args.sample_rate, args.temperature, args.seed, args.seed_offset)
  File "generate.py", line 164, in generate
    model = create_inference_model(ckpt_path, num_seqs, config)
  File "generate.py", line 158, in create_inference_model
    model.load_weights(ckpt_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1248, in load_weights
    status.assert_nontrivial_match()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 998, in assert_nontrivial_match
    return self.assert_consumed()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 975, in assert_consumed
    "".join(unused_attribute_strings)))
AssertionError: Some objects had attributes which were not restored:
    <tf.Variable 'sample_rnn/frame_rnn/upsample:0' shape=(4, 1024, 1024) dtype=float32, numpy=
array([[[-1.02961492e-02,  1.35401851e-02,  1.50977094e-02, ...,
          1.01866096e-03,  5.10610989e-04,  1.87566746e-02],
        [ 8.87395721e-03, -4.18026838e-03, -6.99102599e-03, ...,
          3.04940287e-02, -1.03946663e-02,  2.09112354e-02],
        [ 2.33578612e-03,  1.77005269e-02,  1.46402500e-03, ...,
         -1.09163010e-02, -1.46275619e-02, -6.82321005e-03],
        ...,
        [ 2.34062839e-02,  7.47851795e-03,  3.84401088e-03, ...,
         -2.79776342e-02, -5.57626272e-03,  6.32355595e-03],
        [-2.42233202e-02, -7.10393721e-03, -1.93884352e-03, ...,
         -1.35604087e-02, -8.97351932e-03,  2.98934337e-03],
        [-7.63602601e-03,  3.31373848e-02,  4.70729574e-04, ...,
          3.60660697e-03,  2.51634941e-02,  1.27788875e-02]],

       [[ 7.90888385e-04, -3.12626585e-02, -1.91800983e-03, ...,
         -2.86801532e-02, -1.09788710e-02, -1.92267634e-02],
        [ 8.18298850e-03,  2.17494778e-02, -1.31149981e-02, ...,
          1.70598291e-02, -4.57543228e-03,  4.49129613e-03],
        [-1.42808305e-02, -7.20372563e-03,  1.13683217e-03, ...,
         -3.27150226e-02, -7.19945692e-03,  3.56810377e-03],
        ...,
        [-1.28457043e-02,  1.22231981e-02, -3.25182686e-03, ...,
         -1.34714535e-02, -9.11022816e-03, -2.62970291e-02],
        [-1.67476721e-02,  1.26866661e-02, -7.53369601e-03, ...,
         -7.10430043e-03,  1.64546054e-02, -1.77345611e-02],
        [-2.11791955e-02,  2.27067154e-03,  1.12983892e-02, ...,
         -1.88266076e-02,  1.00256186e-02, -2.94636320e-02]],

       [[-3.47011723e-02, -2.10044496e-02, -5.35532739e-03, ...,
         -8.72646458e-04,  1.23625691e-03,  9.46586806e-05],
        [ 8.24875291e-03, -3.31384689e-02,  1.78510528e-02, ...,
          1.44131845e-02,  2.74074776e-03, -1.71584859e-02],
        [ 7.65335234e-03, -1.22760180e-02,  1.58619806e-02, ...,
         -3.30588868e-04,  2.30300762e-02,  9.01468098e-03],
        ...,
        [ 2.68938299e-03, -1.40413400e-02, -2.10206192e-02, ...,
          2.21681856e-02, -2.58824211e-02,  1.42331515e-02],
        [ 1.94714218e-03, -1.04962348e-03,  1.70364808e-02, ...,
         -1.20551186e-02, -5.75437723e-03, -1.83531549e-02],
        [-1.18572414e-02,  1.84859596e-02, -1.52747957e-02, ...,
          2.44354509e-04, -1.44815380e-02,  1.78436679e-03]],

       [[-3.39218825e-02, -1.77963041e-02, -2.75604390e-02, ...,
          1.53806815e-02,  2.57573631e-02,  3.56114772e-03],
        [-3.40288728e-02, -1.82274655e-02,  1.40822551e-03, ...,
          4.86909645e-03, -1.64082851e-02,  2.20462610e-03],
        [-5.24610840e-03, -1.92433354e-02,  1.91187691e-02, ...,
         -4.68099862e-03,  1.86212994e-02,  2.83861328e-02],
        ...,
        [-6.23152545e-03,  5.05297771e-03, -1.06918439e-02, ...,
          1.04744453e-02,  1.99548360e-02, -1.57663561e-02],
        [ 3.34415659e-02, -1.70691370e-03, -1.00803738e-02, ...,
         -1.48876915e-02, -5.55169024e-03, -2.88231717e-03],
        [-3.79145518e-03,  4.98119649e-03,  2.04012338e-02, ...,
          1.38682462e-02,  3.17192413e-02,  8.98275711e-03]]],

**Comment by relativeflux** [comment]
Hi there,

I assume this is the generate.py script... Could you post the exact script call that caused this, with the parameters you used?

**Comment by curingd** [comment]
Thanks - I did work out that the `checkpoint_path` needed to be changed to `model.ckpt-8.index` (that seemed to be the last checkpoint that was saved in the predict folder. Should I have just put `model.ckpt-8` then? I'll try again with this if necessary.

The code was:

`!python generate.py \
  --output_path ./generated/default/test.wav \
  --checkpoint_path ./logdir/default/predict/model.ckpt-8.index \
  --dur 8 \
  --sample_rate 11025 \
  --temperature 0.1 \
  --config_file ./default.config.json`

Thanks!

**Comment by relativeflux** [comment]
Ah, I can see what your problem is. You've passed `model.ckpt-8.index`. You don't actually need any extension, if you look at the section on checkpoints in the notebook it explains that a checkpoint is in fact multiple files, but you don't need an extension. Sorry, that can be confusing! So just pass `--checkpoint_path ./logdir/default/predict/model.ckpt-8`.

**Comment by curingd** [comment]
Runs great now, thanks!

**Comment by relativeflux** [comment]
No problem. Generation stage is the slowest part of the whole thing currently, we are working on speeding things up. Also, you'll probably need to train for quite a few epochs before you get anything useful, at early stages it'll likely just be white noise. Usually about 15 - 20 epochs before anything decent appears, and usually more than 100 before you'll get anything really interesting. Although there are updates coming soon (next 2 weeks) that will improve training times.
