### ISSUE TITLE
Generated output issue

### ISSUE THREAD

**Issue by CASE-WESTERN** [rncm-prism/prism-samplernn#30]
Hi,

apologies if this is a basic issue, but I'm running the Colab notebook with a subscription. 

I seem to be getting somewhere with the model training, but when it comes to output, there's issues.

Firstly the checkpoint path given under generate.py seems to be referencing a location that doesn't exist, with a 2020 date. If I change it to /logdir/default/27.12.2021_01.15.26/model.ckpt-10.index, which aligns with what I have, it does seem to try and export but the result is a tiny 108kb file named default_e=10_t=0.95.wav, rather than the set "test2.wav". 

My training settings are as follows:
!python train.py \
  --data_dir ./chunks \
  --num_epochs 250 \
  --batch_size 10 \
  --max_checkpoints 2 \
  --checkpoint_every 10 \
  --output_file_dur 10 \
  --sample_rate 11025

And my generate is:
!python generate.py \
  --output_path ./generated/default/test2.wav \
  --checkpoint_path ./logdir/default/27.12.2021_01.15.26/model.ckpt-10.index \
  --dur 10 \
  --sample_rate 11025 \
  --temperature 0.9 \
  --config_file ./default.config.json

Any help would be really appreciated. Cheers!

**Comment by CASE-WESTERN** [comment]
Here's the result for hitting generate.py FWIW

2021-12-28 00:01:46.130675: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Traceback (most recent call last):
  File "generate.py", line 150, in <module>
    main()
  File "generate.py", line 146, in main
    args.sample_rate, args.temperature, args.seed, args.seed_offset)
  File "generate.py", line 98, in generate
    model = create_inference_model(ckpt_path, num_seqs, config)
  File "generate.py", line 74, in create_inference_model
    model.load_weights(ckpt_path).expect_partial()
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./logdir/default/20.12.2020_06.15.46/model.ckpt-14

**Comment by relativeflux** [comment]
@CASE-WESTERN Hi, Perhaps the error arises because of this line:

`--checkpoint_path ./logdir/default/27.12.2021_01.15.26/model.ckpt-10.index`

Specifically the checkpoint name, `model.ckpt-10.index` - you have an extension, `.index`, and you don't need that... Individual checkpoints exist as multiple files on disk (an index file, which contains metadata, and one or more data files, which contain the actual values for the different model variables), but they are always referenced without any extension.

It seems odd that it seems to be looking for a different checkpoint. But I hope that fixes it, let me know if not.

**Comment by CASE-WESTERN** [comment]
Removing the .index seems to be working!

Is checkpoint_path something that should be automatically updated with the most updated training model, or is the 20.12.2020 I see a placeholder that I need to manually update?

Unrelated, any reason why the training will cut out/"finish" every 5 epochs, even if num_epochs is currently at 250? 

Thanks again!

**Comment by relativeflux** [comment]
Glad to be of some help. Perhaps this further issue is related to the `--early_stopping_patience` param. If the validation loss goes in the wrong direction for more than the number of epochs specified by this param (the default is 5) then the training will automatically stop. By 'wrong direction' I mean if it rises whilst the training loss continues to descend. This indicates overfitting.

How big is your dataset? Ideally you want >2000 audio chunks. A large chunk overlap can help increase the dataset size. I notice that your batch size is only 10, which is definitely too small. That - in addition to a small dataset - will almost certainly result in overfitting, which means the early stopping will kick in.

You can examine the progress of training by running TensorBoard. Navigate to the top level of the repository at the command line and run:

`tensorboard --logdir=logdir/default --port=6006`

It will open in your default browser on localhost:6006 (change the port to whatever you like). Kill it with `ctrl C`. You'll see the different timestamped runs listed on the left in the main panel, just select the one you want. In the charts panel select epoch_loss, that will show graphs for the training and validation losses for each run.

If you don't specify an id for the training then it will use the default, which is just `default`. Specifying an id will cause a new folder with that name to be generated under logdir. For each 'run' using the same id a subfolder in that folder will be generated, named with a timestamp, with the format `dd.mm.yy_hh.mm.ss`. You don't need to modify these. If `--resume` is `True` (which is the default) then the training will pick up from the last saved checkpoint (or you can specify a particular checkpoint, with `--resume_from`). A new timestamped folder will still be created, however.

**Comment by CASE-WESTERN** [comment]
I've noticed the training tends to deviate from accuracy and then improve, but the highest I've seen so far is 0.65

My data set might be the issue. It's around 40 minutes in length, but with the sample size left to default I was only getting around 300 chunks to work with. I'll shrink the chunk size down to something more fitting and see how she makes out.

This is fascinating stuff and I can see how fine tuning will become very much an art. 

Cheers!
