### ISSUE TITLE
Generated audio is clipping

### ISSUE THREAD

**Issue by LottieSebes** [rncm-prism/prism-samplernn#32]
Hi @relativeflux, 

I'm really enjoying using the notebook, thanks for all your efforts. I've found that often audio I generate is clipping - is this a common problem and do you have any suggestions for how to fix it?
And tips would be greatly appreciated, thanks!

**Comment by relativeflux** [comment]
@LottieSebes  Hi there and thanks for getting in touch. I do get clipping occasionally, but it's hard to say what the reason might be. What sort of dataset are you training on? And what is the sample rate? Also are you using linear quantization as opposed to the default mu-law quantization? The latter generally trains better, but clipping can be more of a problem.

**Comment by LottieSebes** [comment]
Thanks for your reply! I'm using recordings of speaking voice. Initially I was using the recommended low sample rate of 11025 but I was already having the clipping problem so I increased slowly all the way up to 44.1khz and still haven't encountered additional problems other than the fact that of course the processing time is a lot longer, which is fine. I'm also using the default mu-law quantisation.

**Comment by relativeflux** [comment]
@LottieSebes Hi, apologies for not getting back to you on this before now, sounds like it's working with higher sample rates. The upcoming mixed-precision training will greatly increase training time speed (> 3x), so watch out for that, coming very soon (the mixed-precision2 branch is where it currently resides, check that branch out if you what to try it before it's completely merged).

In general I'd say higher sample rates are the way to go for better quality generated outputs.
