### ISSUE TITLE
Incorrect checkpoint format

### ISSUE THREAD

**Issue by 01778680** [rncm-prism/prism-samplernn#33]
I am receiving this error after running the code in the google colab notebook. This program seems to generate three different files in the logdir/default/xx.xx.xxxx/train/ directory, none of which work with the generate script.

`Traceback (most recent call last):`
  `File "/content/prism-samplernn/generate.py", line 150, in <module>`
    `main()`
  `File "/content/prism-samplernn/generate.py", line 145, in main`
    `generate(args.output_path, args.checkpoint_path, config, args.num_seqs, args.dur,`
 `File "/content/prism-samplernn/generate.py", line 98, in generate`
    `model = create_inference_model(ckpt_path, num_seqs, config)`
 `File "/content/prism-samplernn/generate.py", line 74, in create_inference_model`
   `model.load_weights(ckpt_path).expect_partial()`
  `File "/usr/local/lib/python3.9/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler`
    `raise e.with_traceback(filtered_tb) from None`
  `File "/usr/local/lib/python3.9/dist-packages/h5py/_hl/files.py", line 567, in __init__`
    `fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)`
  `File "/usr/local/lib/python3.9/dist-packages/h5py/_hl/files.py", line 231, in make_fid`
    `fid = h5f.open(name, flags, fapl=fapl)`
  `File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper`
  `File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper`
  `File "h5py/h5f.pyx", line 106, in h5py.h5f.open`
`OSError: Unable to open file (file signature not found)`

**Comment by relativeflux** [comment]
The path to the logdir shouldn't reference the train directory but just the date+time-stamped directory above. So you'll just want `logdir/default/xx.xx.xxxx`. But you need to actually reference a checkpoint, which you do through the checkpoint name, even though checkpoints are (potentially) multiple files on disk. So something like `logdir/default/xx.xx.xxxx/model.ckpt-10`.

The cell for loading Tensorboard referenced the `logdir/default/xx.xx.xxxx/train` directory as the logdir, that might have caused some confusion. That's now been changed to the correct path.

**Comment by 01778680** [comment]
I have used the xx.xx.xxxx directory as the logdir and it provided me with the same error message. I am not seeing any files such as `logdir/default/xx.xx.xxxx/model.ckpt-10`.

**Comment by relativeflux** [comment]
Checkpoint files are generated at the end of every epoch by default (the `checkpoint_every` parameter controls that).

Checkpoints are saved to a folder named with the current date and time, separated by an underscore, something like this:

`logdir/default/26.07.2020_20.48.51/model.ckpt-100`

Also if you give your training session an id (the `id` param to train.py) it will generate a subfolder under the logdir with that name.

Could you post how you are running train.py, and also generate.py in the Notebook?

**Comment by relativeflux** [comment]
Ah, if you are running the script in the Notebook as it is then it has `checkpoint_every` set to 10. So it will only save a checkpoint (and any test audio, automatically generated from it) every 10 epochs. The default value for that param is 1. So either set it to 1, or delete the parameter from the script call. You should then see checkpoint files generated for each epoch (although watch your storage! They can get big).

One thing to keep in mind that the Notebook is intended as an environment to test how to run PRiSM SampleRNN, and shouldn't be relied on for production quality results. Unless you use Colab Pro, but even then it's not a perfect environment.

**Comment by 01778680** [comment]
I probably should have been more specific, my problem is that the train.py script is generating files such as `model.ckpt-10.data-00000-of-00001` and `model.ckpt-10.index` rather than `model.ckpt-10`. When I use either of these files in the generate script, I receive the error message provided above. I believe that the train.py script is not correctly formatting the checkpoints, and it is causing me to be unable to use the generate script. Here are the commands I have been using:
`!python train.py \`
  `--data_dir ./chunks \`
  `--num_epochs 10 \`
  `--batch_size 51 \`
  `--max_checkpoints 5 \`
  `--checkpoint_every 2 \`
  `--output_file_dur 5 \`
  `--sample_rate 11025`

`!python generate.py \`
  `--output_path ./generated/default/test.wav \`
  `--checkpoint_path ./logdir/default/30.04.2023_02.17.00/one-of-the-checkpoint-files \`
  `--dur 10 \`
  `--sample_rate 11025 \`
  `--temperature 0.9 \`
  `--config_file ./default.config.json`

**Comment by 01778680** [comment]
I also see that there is a third file titled `checkpoint` which has this inside of it:
`model_checkpoint_path: "model.ckpt-10"`
`all_model_checkpoint_paths: "model.ckpt-10"`
I am not really sure what this means, as I do not see this anywhere.

**Comment by relativeflux** [comment]
OK, hopefully I can solve the problem this time! It looks like it's due to one of the peculiarities of TensorFlow, which SampleRNN 'inherits'.

When checkpoints are generated there are actually multiple files created on disk. So, for (let's say) epoch 10 you will have a file `model.ckpt-10.index` which is like a header (meta information). Then you will have one or more files containing the actual training data. So you might have two such files, named as follows:

```
model.ckpt-10.data-00000-of-00002
model.ckpt-10.data-00001-of-00002
```

It looks like this is what you are seeing, which is exactly as expected. BUT: what you pass to the generate.py script is just `model.ckpt-10` - just the checkpoint name, with no extension. So:

```
!python generate.py \
--output_path ./generated/default/test.wav \
--checkpoint_path ./logdir/default/30.04.2023_02.17.00/model.ckpt-10 \
--dur 10 \
--sample_rate 11025 \
--temperature 0.9 \
--config_file ./default.config.json

```
You can ignore the file named just `checkpoint`, that's just another of TensorFlow's standard storage files when generating checkpoints.

**Comment by 01778680** [comment]
Perfect, this fixed it!
