### ISSUE TITLE
ValueError: time data 'train' does not match format '%d.%m.%Y_%H.%M.%S'

### ISSUE THREAD

**Issue by curingd** [rncm-prism/prism-samplernn#4]
Hi again,

I've tried running the training code again with your updated `train.py` and with:

`!python train.py \
  --data_dir ./chunks \
  --num_epochs 100 \
  --batch_size 198 \
  --checkpoint_every 100 \
  --output_file_dur 8 \
  --sample_rate 11025 \
  --generate False`

I used the new `--generate False` command to try to speed things up and I've received the following error:

Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main()
  File "train.py", line 219, in main
    initial_epoch = get_initial_epoch()
  File "train.py", line 212, in get_initial_epoch
    latest_checkpoint = get_latest_checkpoint(logdir)
  File "train.py", line 165, in get_latest_checkpoint
    dt = datetime.strptime(f, '%d.%m.%Y_%H.%M.%S')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'train' does not match format '%d.%m.%Y_%H.%M.%S'

Do you have any suggestions? Pretty sure I copied the new train.py properly.

All best,
David

**Comment by relativeflux** [comment]
HI there,

Is this the train-keras branch? That's almost ready to be merged to master, but I think what you're seeing is due to the fact that the format for the checkpoint directories has changed - the `train` and `predict` directories have been removed, replaced with timestamped directories for each training 'run' under a given id. I guess you still have those directories around from a previous session, juts remove the directory with the id and start again. Let me know if that's still not working.

Chris

**Comment by relativeflux** [comment]
Checkpointing now happens at the end of each epoch, or the epoch specified by checkpoint_every, so set the latter to 5 or something - 100 is going to be too, most likely.

**Comment by curingd** [comment]
It's working now, thanks! Knew I'd be doing something silly...

**Comment by curingd** [comment]
Just one more thing (again, I'm probably doing something stupid...): it's now training, but whenever I stop it / Colab times out from running overnight and then I resume the training, the accuracy values appear to start again, from less than 1%, as if the training had started from scratch, even though I'm using `--resume True`...

Is there a way to fix this? Or maybe I just need to upgrade to the Pro version of Colab if I'm going to keep running it on my laptop!

David

**Comment by curingd** [comment]
I should say that the epochs do resume from where they left off, but the accuracy rates are as if it had started from scratch.

**Comment by relativeflux** [comment]
Hi David,

Thanks for the update. The Colab notebook works with the current master branch, not the train-keras branch - which is still not guaranteed bug free, I should add. The latter branch will be merged to master in the next week, I will keep this this issue open and update when it's ready.

**Comment by relativeflux** [comment]
Hi David,

Sorry for leaving this hanging, I've been on leave. Just to say that there have been major updates recently, still on the `train-keras` branch, but to be integrated into master shortly. Audo generation time is now much faster, c. 3-4 times faster (on Colab, maybe even faster depending on your GPU). All updates are listed at the top of the README (on that branch).

Chris
